name: Custom Environment Variables
env:
  WORKSPACE_ENVIRONMENT_VARIABLE: workspace
on: [push]
jobs:
  job1:
    env:
      JOB_ENVIRONMENT_VARIABLE: jobs
    runs-on: ubuntu-latest
    steps:
      - env:
          STEPS_ENVIRONMENT_VARIABLE: steps
      - name: Print environment variables
        env:
          COMMAND_ENVIRONMENT_VARIABLE: action_command
        run: |
          echo $COMMAND_ENVIRONMENT_VARIABLE
