name: Environment Variables
env:
  WORKSPACE_ENVIRONMENT_VARIABLE: 'Workspace environment variable'
on: [push]
jobs:
  ubuntu:
    env:
      JOB_ENVIRONMENT_VARIABLE: 'Job environment variable for Ubuntu'
    runs-on: ubuntu-latest
    steps:
      - name: Print custom environment variables from ubuntu-latest
        env:
          STEP_ENVIRONMENT_VARIABLE: 'Step environment variable for Bash'
        run: |
          echo "Accessing environment variables using shell syntax"
          echo "1. $WORKSPACE_ENVIRONMENT_VARIABLE"
          echo "2. $JOB_ENVIRONMENT_VARIABLE"
          echo "3. $STEP_ENVIRONMENT_VARIABLE"
          echo ""
          echo "------------------------------------------------------"
          echo ""
          echo "Accessing environment variables using env syntax"
          echo "4. ${{ env.WORKSPACE_ENVIRONMENT_VARIABLE }}"
          echo "5. ${{ env.JOB_ENVIRONMENT_VARIABLE }}"
          echo "6. ${{ env.STEP_ENVIRONMENT_VARIABLE }}"
  windows:
    env:
      JOB_ENVIRONMENT_VARIABLE: 'Job environment variable for Windows'
    runs-on: windows-latest
    steps:
      - name: Print custom environment variables from windows-latest
        env:
          STEP_ENVIRONMENT_VARIABLE: 'Step environment variable for PowerShell'
        run: |
          echo "Accessing environment variables using shell syntax"
          echo "1. $Env:WORKSPACE_ENVIRONMENT_VARIABLE"
          echo "2. $Env:JOB_ENVIRONMENT_VARIABLE"
          echo "3. $Env:STEP_ENVIRONMENT_VARIABLE"
          echo ""
          echo "------------------------------------------------------"
          echo ""
          echo "Accessing environment variables using env syntax"
          echo "4. ${{ env.WORKSPACE_ENVIRONMENT_VARIABLE }}"
          echo "5. ${{ env.JOB_ENVIRONMENT_VARIABLE }}"
          echo "6. ${{ env.STEP_ENVIRONMENT_VARIABLE }}"
