name: Environment Variables
env:
  WORKSPACE_ENVIRONMENT_VARIABLE: workspace
on: [push]
jobs:
  job1:
    env:
      JOB_ENVIRONMENT_VARIABLE: jobs
    runs-on: ubuntu-latest
    steps:
      - name: Print custom environment variables
        env:
          STEP_ENVIRONMENT_VARIABLE: step
        run: |
          echo "Accessing environment variables in run command"
          echo \$WORKSPACE_ENVIRONMENT_VARIABLE=$WORKSPACE_ENVIRONMENT_VARIABLE
          echo \$JOB_ENVIRONMENT_VARIABLE=$JOB_ENVIRONMENT_VARIABLE
          echo \$STEP_ENVIRONMENT_VARIABLE=$STEP_ENVIRONMENT_VARIABLE
          echo "------------------------------------------------------"
          echo "Accessing environment variables using env context"
          echo \${{ env.WORKSPACE_ENVIRONMENT_VARIABLE }}=${{ env.WORKSPACE_ENVIRONMENT_VARIABLE }}
          echo \${{ env.JOB_ENVIRONMENT_VARIABLE }}=${{ env.JOB_ENVIRONMENT_VARIABLE }}
          echo \${{ env.STEP_ENVIRONMENT_VARIABLE }}=${{ env.STEP_ENVIRONMENT_VARIABLE }}
